### ISSUE TITLE
Access to DWR Dev Server

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing-query#1]
DWR contact:
Aaron Heyman
aaronheyman@utah.gov
801.538.4823

**Comment by stdavis** [comment]
Test version of the app should be available here: https://dwrapps.dev.utah.gov/dwrefdb/query/index.html

It doesn't do anything yet but I've confirmed that I can deploy to the test server.

@nathankota Do you want to confirm that you can access it and then close the issue?

**Comment by nathankota** [comment]
Access to https://dwrapps.dev.utah.gov/dwrefdb/query/index.html confirmed!
