### ISSUE TITLE
Submitted Filter Expected Behavior - Table

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing-query#10]
### User Story
As a user, once I have entered valid filter criteria, I must click a Submit button to enable the filter and the following occurs in the table for each survey event that match the filter criteria:

### Details
- The table is populated with data from the following fields:
   - [x] Wildlife.WildAdmin.SamplingEvents.EVENT_DATE
   - [x] Wildlife.WildAdmin.SamplingEvents.OBSERVERS
   - [x] UDWR.Streams.WaterName
   - [x] UDWR.Streams.DWR_WaterID
   - [x] UDWR.Streams.ReachCode
   - [x] Wildlife.WildAdmin.Stations.STATION_ID
   - [x] Wildlife.WildAdmin.Fish.SPECIES_CODE (if multiple species, comma delimited list)
   - [x] Wildlife.WildAdmin.Equipment.TYPE (if multiple equipment, comma delimited list)

- [x] Records are returned in decreasing temporal order

**Comment by stdavis** [comment]
> * [ ] UDWR.Streams.WaterName
> * [ ] UDWR.Streams.DWR_WaterID
> * [ ] UDWR.Streams.ReachCode
The relationship between sampling events and these datasets are not in the database. It would have to be generated by some sort of script as suggested in #14.

**Comment by stdavis** [comment]
Streams data is blocked by: https://github.com/agrc/electrofishing/issues/195

**Comment by ToddVolkening** [comment]
Still needs to be populated for queried and downloaded event data with the DWR_WaterID field that's present in UDWR.Streams.DWR_WaterID.  Thank you

~CW and TV

**Comment by stdavis** [comment]
I went ahead and replaced permanent id with DWR_WaterID in the grid and then added DWR_WaterID to the download CSVs. Download tool is already updated. Changes to the app (grid) will be pushed with the next deploy...

**Comment by stdavis** [comment]
This should be ready to test in v0.10.0 on the test server.

**Comment by nathankota** [comment]
@ToddVolkening and Craig - this looks good to me, but will wait for your feedback before closing this issues.

**Comment by ToddVolkening** [comment]
We did some preliminary testing and things look great.  Thanks!

~CW and TV
