### ISSUE TITLE
Location Filter

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing-query#14]
### User Story
As a user, I can start typing a stream/lake name to refine selections, then add one or more stream/lake values to a list of locations to filter before submitting the filter. I may remove unwanted values from the list of locations. 

### Details
- The location search functions exactly like the one on the [data entry application's map](http://test.mapserv.utah.gov/electrofishing/)

![streamlakename](https://user-images.githubusercontent.com/15659642/53835937-e5158280-3f4b-11e9-95a7-228b05a031a0.JPG)

- Each selected location value gets "docked" in the filter, and values can be removed by clicking the 'x' next to a location name, similar to:

![multipleselections](https://user-images.githubusercontent.com/15659642/53836101-5bb28000-3f4c-11e9-98fe-7b713c9425df.JPG)

### Database fields
The Location filter acts on the following attribute:
- UDWRStreams.WaterName

**Comment by stdavis** [comment]
I don't see any relation between stations and WaterName. Not sure how to make this query work.

**Comment by stdavis** [comment]
Possible solution: Write a post-process gp script that generates a many-to-many relationship table that links survey events to water names. The relationships would have to be built by using some sort of proximity.

**Comment by stdavis** [comment]
Blocked by: https://github.com/agrc/electrofishing/issues/195

**Comment by ToddVolkening** [comment]
Looks good.  Thank you.

~CW and TV
