### ISSUE TITLE
Date Filter

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing-query#15]
### User Story
As a user, I may select a begin and end date to filter survey event data. If I click Submit with an incomplete date filter an error message will prompt me to submit a valid filter, and highlight the incomplete date field(s).

### Details
- Both begin and end date must be fulfilled to create a date range, even if it is a single day
- End date must be greater than Begin date
- The date fields function exactly the same as the _Collection Date_ field on the _Location_ tab of the [data collection app](http://test.mapserv.utah.gov/electrofishing/)

![collectiondate](https://user-images.githubusercontent.com/15659642/53835319-6835d900-3f4a-11e9-9702-fc4985de4686.JPG)

### Database Fields
This filter is applied to the following database field:
- Wildlife.WildAdmin.SamplingEvents.Event_Date

**Comment by nathankota** [comment]
> - End date must be greater than Begin date

Is it possible to limit the filter to only allow positive data ranges to be selected, such as only enabling the Submit button when there is a positive date range because...

When a positive date range is chosen the filter returns data:
![image](https://user-images.githubusercontent.com/15659642/57390832-7090d700-717a-11e9-8e61-df002f54fd1b.png)

but if the same dates are selected in reverse order to show a negative date range, the filter does not return any data:
![image](https://user-images.githubusercontent.com/15659642/57390960-af269180-717a-11e9-8233-0fa5d0fbd676.png)

**Comment by stdavis** [comment]
Great catch. Can do.
