### ISSUE TITLE
UtahID Authentication

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing-query#182]
The app needs to be secured by UtahID. An identity provider is already set up in GCP. 

Currently, [agrc/firebase-auth-arcgis-server-proxy](https://github.com/agrc/firebase-auth-arcgis-server-proxy) is used to secure the ArcGIS Server services via a [service worker](https://firebase.google.com/docs/auth/web/service-worker-sessions). I assume that we will need to do the same thing in the new app but I'm not 100% sure.

Blocked by: https://github.com/agrc/kitchen-sink/issues/256

**Comment by stdavis** [comment]
I remembered today that they asked me to set up a publicly accessible, read-only map service for the same data that this app uses long after this app was built. I'm not sure that we even need authentication for this application anymore. I sent an email to them today asking this question.

**Comment by stdavis** [comment]
Craig said that they still want to have the application secured.

**Comment by steveoh** [comment]
What is the blocked label in reference to?

**Comment by stdavis** [comment]
I'm assuming this was closed inadvertently. I don't believe that we have this implemented yet.

**Comment by steveoh** [comment]
https://github.com/agrc/electrofishing-query/commit/212e73ef591aefae02b1eeed6f2e355da6debd3d 

Looks like a bug to me. This has a refs token.

**Comment by stdavis** [comment]
This is done in the new app.
