### ISSUE TITLE
Download Results

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing-query#186]
Call the "Download" async gp task with the selected event ids and format. Poll for results and display the download link.

Allow the user to select the format type (CSV or FGDB).

**Comment by steveoh** [comment]
Is this task on our servers?

**Comment by stdavis** [comment]
Yes, it's on the same server as the feature service which is the WRI server. I believe that there are test services as well.

**Comment by steveoh** [comment]
Ok, I don't consider those our servers but good to know.
