### ISSUE TITLE
Layer Selector

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing-query#188]
![image](https://github.com/user-attachments/assets/7875830d-593a-4ba6-a555-98f588b5a860)

I'm not sure why the Esri streets are in there. I don't see any features outside of the state. It looks like it may have been a copy/paste from the UGS app.

My vote is to replace Esri streets with Lite and continue to keep Hybrid as the default.

**Comment by stdavis** [comment]
This is done in the new app.

**Comment by steveoh** [comment]
The default isn't correct unless you changed it. I hadn't read this issue when I chose the default.

**Comment by stdavis** [comment]
Good catch. We need to change the default to Hybrid.
