### ISSUE TITLE
Navigate between data entry forms and filter

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing-query#20]
### User Story ###

As a user, I must be able to easily easily navigate from any page on the [data collection site](http://test.mapserv.utah.gov/electrofishing/) to the filter, and vice versa.

### Details ###
- [x] "Search" button on data collection header to navigate to filter
- [x] "Enter Data" button on the filter header to navigate to date entry part of app

**Comment by stdavis** [comment]
I'm going to propose that these links open the app in a new tab to reduce the chance of a user inadvertently losing a complicated filter or some data in the data entry app.

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/59130974-31e36d80-892e-11e9-8f3f-89758a8f340e.png)
![image](https://user-images.githubusercontent.com/1326248/59131049-6eaf6480-892e-11e9-92b2-9fc7b3a9c609.png)

**Comment by nathankota** [comment]
Eric will submit a SN ticket due to inability to access data entry site.

**Comment by stdavis** [comment]
FYI - The data entry site is deployed but I don't think that it's working properly yet. I'm guessing that it's because it's on a different URL now but haven't checked into it yet.

**Comment by nathankota** [comment]
Seems like they had an old url. This one works for everyone https://dwrapps.dev.utah.gov/dwrefdb/dataentry/
