### ISSUE TITLE
Filter Zoom

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing-query#26]
Related to #11 

Current Behavior:

- Submit filter
- Zoom and/or pan map to location other than extent of filtered results
- Alter filter and submit
- Map seems to zoom to the center of the new filter results, but at the current extent

Expected Behavior:
- Submit filter
- Zoom and/or pan map to location other than extent of filtered results
- Alter filter and submit
- Zoom to extent of newly-submitted filter

**Comment by stdavis** [comment]
I'm having troubles reproducing. Would you mind giving me the exact filters that you are using?

**Comment by nathankota** [comment]
- Submit date range filter for 5/31/2018 - 6/8/2018 , which will show three stations:
![image](https://user-images.githubusercontent.com/15659642/57625884-fc777a00-7551-11e9-872b-d316f329b775.png)

- Zoom into the middle point, along Big Cottonwood Creek 
![image](https://user-images.githubusercontent.com/15659642/57627357-1797b900-7555-11e9-9855-511e7500a5a0.png)

- Change filter end date to 6/30/2018 and submit
- Map moves slightly. If possible, it should zoom to the extent of the new filter.  Even when the filter is cleared and resubmitted, it stays at that zoomed-in scale.

**Comment by nathankota** [comment]
Clients also experienced this. If a filter is implemented, then the map is moved or zoomed, then next time a filter is submitted the map does not zoom to the extent of the new results.

**Comment by ToddVolkening** [comment]
Nailed it.

~CW and TV
