### ISSUE TITLE
Stream Name selection

### ISSUE THREAD

**Issue by ToddVolkening** [agrc/electrofishing-query#27]
When using Stream Name search tool, the polyline depicted on the map disappears when zoom extent is changed. Our guess is this was not supposed to happen

**Comment by ToddVolkening** [comment]
When using Stream Name search tool, the polyline depicted on the map disappears when zoom extent is changed.  Our guess is this was not supposed to happen

**Comment by stdavis** [comment]
This actually is intended functionality for that widget. It's intended to get out of the way of the user once it has zoomed to the feature. However, I can turn it off so that the yellow stays until the next search if you would like. Just let me know.

**Comment by ToddVolkening** [comment]
I had an opportunity to speak with Craig W. about this and he indicated, "Please turn on the functionality to allow us to see whether it provides a benefit or, as you stated, just gets in the way".  Thank you!

TV and CW

**Comment by ToddVolkening** [comment]
The modification provided intended benefit.  Thank you

~CW and TV
