### ISSUE TITLE
Zoom extent and table population

### ISSUE THREAD

**Issue by ToddVolkening** [agrc/electrofishing-query#28]
As map zoom extent changes, the tabular records from the original extent should reflect only those in the current zoom extent that meet the original search criteria.   For example, if you zoom out, the tabular results expand; conversely, if you zoom in, the tabular results narrow.

**Comment by nathankota** [comment]
I don't see this in the requirements document. We did talk about selecting stations on the map and having the associated records selected in the table, but the filters are what determine the tabular results.

**Comment by ToddVolkening** [comment]
Spoke with Craig W. about about this and he indicated that "it is fine as is".  Thanks!
