### ISSUE TITLE
Species+Length Filter - negative numbers

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing-query#29]
Disallow entry of negative numbers in Size section of Species and Length filter since there cannot be a negative length measurement.

![image](https://user-images.githubusercontent.com/15659642/58271323-0a46af80-7d49-11e9-9dd6-218d19bec273.png)

**Comment by ToddVolkening** [comment]
1).  Warning needs to remain on screen until a positive value has been entered or the negative value has been removed.  Currently, as soon as you tab to the next field, the negative value warning disappears and allows a users to continue to enter values.

2).  The negative warning banner prompt remains after the filter has been cleared.  

~TV and CW

**Comment by nathankota** [comment]
> 1). Warning needs to remain on screen until a positive value has been entered or the negative value has been removed. Currently, as soon as you tab to the next field, the negative value warning disappears and allows a users to continue to enter values.

Is it okay enough for the Submit button to not be active even after the warning disappears?

> 2). The negative warning banner prompt remains after the filter has been cleared.

I notice that too.

**Comment by stdavis** [comment]
I fixed #2 via fd699a5 and it will be in the next release.

As for #1 - I don't think that it would be a good idea to persist the error message when the focus is on a different input since then it would be confusing as to which input the error message is referencing. However, I can see your point about being able to move on without any indication that there is something wrong with a previous input. To help with this, I added a red color to the input when it is invalid that persists after it loses focus.
![image](https://user-images.githubusercontent.com/1326248/59133868-960a2f80-8936-11e9-96b9-d753c4c641d3.png)

**Comment by ToddVolkening** [comment]
That should work.  We will test further once the server is up and running.  At the moment, we are unable to test due to network issues.

~CW and TV

**Comment by ToddVolkening** [comment]
![EF Filter Negative Numbers](https://user-images.githubusercontent.com/35234370/59625711-3b6f9100-90f7-11e9-83a7-6d5b5d5a4ee3.png)

**Comment by nathankota** [comment]
They would like for the error message to persist above the entry that triggers it, like:
![image](https://user-images.githubusercontent.com/15659642/59874837-77576000-935c-11e9-8182-223a401548a7.png)
Currently, if you click into the adjacent data field the message goes away (unless you add another negative value).

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/61547405-8afff000-aa08-11e9-9541-c0da1dc934f8.png)
Behold the error messages in all of their glory!

**Comment by nathankota** [comment]
For the min/max error, please change "that" to "than"
![image](https://user-images.githubusercontent.com/15659642/62134302-78ee3f00-b29d-11e9-8c22-70800c3167ec.png)

**Comment by nathankota** [comment]
This appears to be working properly and as requested, pending DWR feedback.

**Comment by ToddVolkening** [comment]
This seems to be working other than changing the "that" to a "than".  

~CW and TV

**Comment by nathankota** [comment]
I'll close this and create a new issue for the typo so it doesn't get lost in the comments of this issue.
