### ISSUE TITLE
Station Selection

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing-query#30]
1. Submit a filter that results in multiple stations on map (e.g. Species = BG, Size = 0mm to 100mm)
2. Ctrl-click to select/highlight multiple stations on map
3. A station that was previously highlighted will lose its highlight

![image](https://user-images.githubusercontent.com/15659642/58273447-fbaec700-7d4d-11e9-8f20-34c84b0ed281.png)

**Comment by ToddVolkening** [comment]
Almost there....

Unable to click-deselect a pin on the map, but the click-deselect functionality appears to be working in the table.   The multiple click selection functionality now works as intended.

**Comment by nathankota** [comment]
When ctrl-clicking to deselect highlighted stations, the last pin to be clicked will clear the table, but the pin remains highlighted. Can the pin be un-highlighted on that final click too?

**Comment by nathankota** [comment]
Looks good. Pending DWR testing and review.

**Comment by ToddVolkening** [comment]
Looks good and works as intended. 

CW and TV
