### ISSUE TITLE
Species Selection - clear

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing-query#31]
In the species selection list, can the first (blank) selection have some text so that users know that clicking it will clear any selection that has been made. Text could include "(clear selection)", "(clear)", "(none)", or something similar that fits.

![image](https://user-images.githubusercontent.com/15659642/58274195-99ef5c80-7d4f-11e9-947f-848caa3f742a.png)

**Comment by ToddVolkening** [comment]
Perfect.  Thank you!
~CW and TV
