### ISSUE TITLE
Filter Issues

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing-query#33]
Some issues were found with the implementation of additive filtering:

**Scenario 1:** change in additive (AND) filter not clearing map
- Submit filter where:
    - Species = BG
    - Size from 40 mm - 50 mm
    - RESULT: This works correctly

- Keep species & size filter at 40 mm - 50 mm

- Add Purpose = Depletion estimate 
    -  RESULT: Table clears because there are no matches for this filter, but map still shows at least one point

**Scenario 2:** Do the same filter above with the Purpose added from the start

- Submit filter where:
    - Purpose = Depletion 
    - Species = BG
    - Size from 40 mm - 50 mm
    - RESULT: Returns no data in table, but shows a point in American Fork Canyon

**Scenario 3:**

- Submit filter where:
    - Species = BG and BN
    - Date Range: 5/6/19 - 5/22/19
    - RESULT: Returns values in July 2018

**Comment by nathankota** [comment]
Looks like scenario 3 is fixed, but scenarios 1 and 2 persist:

**Scenario 1**: change in additive (AND) filter not clearing map

Submit filter where:

Species = BG
Size from 40 mm - 50 mm
RESULT: This works correctly
Keep species & size filter at 40 mm - 50 mm

Add Purpose = Depletion estimate

RESULT: Table clears because there are no matches for this filter, but map still shows at least one point

**Scenario 2**: Do the same filter above with the Purpose added from the start
Submit filter where:
Purpose = Depletion
Species = BG
Size from 40 mm - 50 mm
RESULT: Returns no data in table, but shows a point in American Fork Canyon

~~**Scenario 3**:~~
~~Submit filter where:~~
~~Species = BG and BN~~
~~Date Range: 5/6/19 - 5/22/19~~
~~RESULT: Returns values in July 2018~~

**Comment by stdavis** [comment]
Sorry about missing this one. I swore that I tested this in staging (it wasn't happening in my dev environment) but I guess that I missed it. I _think_ that I've got it fixed this time in v0.5.1 which I just pushed. Would you mind testing again?

**Comment by ToddVolkening** [comment]
Scenario 1 and 2 still aren't working properly.   

~CWTV

**Comment by nathankota** [comment]
In my testing just now, all three scenarios worked properly. Can you guys please try again and do some screen grabs of what you're seeing?

**Comment by stdavis** [comment]
Make sure that you are testing v0.5.**1**

**Comment by ToddVolkening** [comment]
We just tested this out on the 0.6.0  and it appears to be working properly.  Thanks!

~CW and TV
