### ISSUE TITLE
Collapse Filter Pane

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing-query#34]
Some filters result in points hiding behind the filter pane. Can the filter pane be collapsed when the Submit button is clicked?

**Comment by stdavis** [comment]
Would this be collapsed enough?
![image](https://user-images.githubusercontent.com/1326248/58565842-add20d00-81ec-11e9-99e0-44d687b0caeb.png)
I would make all of the filters collapsed when the user clicks "Submit".

**Comment by nathankota** [comment]
I think it is good, and have asked DWR team to confirm.

**Comment by nathankota** [comment]
Let's go with this for now and let them test and give feedback.
