### ISSUE TITLE
No filters allowing user to select or populate filter

### ISSUE THREAD

**Issue by ToddVolkening** [agrc/electrofishing-query#36]
In version 0.6.0 the ability to select from any of the filters does is not functioning.  No drop downs present.  Two error messages appear.  First message = "There was an error populating the grid!".  The second error message = Error querying features!  Unable to load https//.....status:0

**Comment by steveoh** [comment]
that is definitely caused by the network outage. It is probably best to stop testing for now until DTS figures out the networking issues.

**Comment by nathankota** [comment]
F5 restored back to settings from earlier date. Resume testing.
