### ISSUE TITLE
Typo on Species/Length filter error

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing-query#39]
Please change "that" to "than" on the negative number error

![image](https://user-images.githubusercontent.com/15659642/62311587-6153b980-b449-11e9-8043-afb38f5d1c5d.png)

**Comment by nathankota** [comment]
Has this been deployed to https://dwrapps.dev.utah.gov/dwrefdb/query/ or should I be testing on a different site?

**Comment by stdavis** [comment]
No, it has not yet been deployed. I'll move it to "Validate (To Do)" once I deploy.

**Comment by ToddVolkening** [comment]
Fixed.  Thank you.

~TV and CW
