### ISSUE TITLE
Query tool error

### ISSUE THREAD

**Issue by ToddVolkening** [agrc/electrofishing-query#41]
Sorry I couldn't figure out how to submit an entry for the query portion of the application.  Please move to the appropriate locale if needed.

The Electrofishing Rivers and Streams Data Queries tool is not working and we keep receiving an error statement.  As a result we are unable to do further testing on the functionality of the query tool.

We have received several different error messages but attached is a screen shot of the most consistent and common error message.

![Query error_010620](https://user-images.githubusercontent.com/35234370/71936267-27a87c80-3166-11ea-8df7-d12dfa05629d.PNG)

**Comment by stdavis** [comment]
This appears to be working for me. Is it still broken for you?
![image](https://user-images.githubusercontent.com/1326248/72537802-00bf0a00-383a-11ea-968f-6e809078175d.png)

**Comment by steveoh** [comment]
i think you transferred this issue. do you want to move this comment and close this issue?

**Comment by stdavis** [comment]
Yes, I moved the issue and it's in the correct repo now. This is the correct repo.

No, it should not be closed since it hasn't yet been resolved.

**Comment by ToddVolkening** [comment]
Its appears to be working again.  This error was likely tied to the DWR Collars server issue, which has been resolved.
