### ISSUE TITLE
Add Equipment Type to filter

### ISSUE THREAD

**Issue by ToddVolkening** [agrc/electrofishing-query#42]
We realize this likely an enhancement..

Add Equipment Type as a filter option in the query drop down.

TV and CW

**Comment by stdavis** [comment]
@ToddVolkening Would you mind giving me the specific table and field that this filter should use? The Equipment table has several fields that seem like they may fit and I'm not sure which one is correct. Or perhaps this is actually a request for multiple filters for multiple different fields?

**Comment by stdavis** [comment]
Actually, I just noticed the `TYPE` field in the Equipment table. I'm going to assume that is the field (and associated domain) that you would like this filter to use. Please let me know if this is not a correct assumption.

**Comment by ToddVolkening** [comment]
Hi Scott,

I believe you're on the right track, but to be safe, I'm looping in Craig
Walker (cc'd) to confirm your assumption.  I've added a screenshot of the
GitHub submission for your reference, Craig.

[image: Screenshot 2024-11-06 065158.png]



[image: Photo]

Todd Volkening
Senior GIS Analyst
M: (801) 244-5878
E: ***@***.*** ***@***.***>

Utah Department of Natural Resources
Division of Wildlife Resources
[image: Facebook icon] <http://facebook.com/UtahDWR>[image: Twitter icon]
<https://twitter.com/UtahDWR>[image: Youtube icon]
<https://www.youtube.com/user/UDWR>[image: Instagram icon]
<https://www.instagram.com/utahdwr/>
wildlife.utah.gov

The content of this email is confidential and intended for the recipient
specified in the message only. It is strictly forbidden to share any part
of this message with any third party without the written consent of the
sender. If you received this message by mistake, please reply to this
message and follow with its deletion so that we can ensure such a mistake
does not occur in the future.
