### ISSUE TITLE
Add more Species/Length selections

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing-query#45]
In the `Species and Length` filter, increase the number of selection options from 4 to 8.

![image](https://user-images.githubusercontent.com/15659642/109693972-8178bc80-7b47-11eb-9fa2-fc1048eb5981.png)

**Comment by stdavis** [comment]
You may now add unlimited number of rows:
![Image](https://github.com/user-attachments/assets/87be3ca6-4b32-4e60-9674-f2980a55c589)
