### ISSUE TITLE
Data Download

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing-query#5]
### User Story
As a user, I would like a Download Data button to either download csv files of data for all records returned by a filter, or the records I have selected from the map #188 or the table #191. I would like the ability to select which data tables to download, or download all.

### Details
- [x] separate csv files generated for db tables, with some constant fields from other tables
- [x] this [sheet](https://docs.google.com/spreadsheets/d/1eVhcqWaA7ZWe2ywph0KNVXAKiW9hGVJWNuM9P6lb_hk/edit#gid=310548436) contains the data "map" for each csv. The client's description is:
    
_Each tabbed sheet, excluding the "Master" tab, represents what we suggest would be a unique CSV table.  Each table has columns A - H as constant fields to allow end users to merge tables using statistical software sort functions. Color coding indicates where on the Master tab segments of each table (tab) were derived.  Additionally, we have included a few comments/questions regarding some of the variables._

**Comment by stdavis** [comment]
> I would like the ability to select which data tables to download, or download all.

What's the use case for this? I wonder if the complexity that this would add to the UI would be more headache than it's worth. Could we just give them all tables and let them select the ones they want from the zip file after downloading?

**Comment by ToddVolkening** [comment]
Providing zip files with all tables for selected events would be perfect.  

~CW and TV

**Comment by nathankota** [comment]
Pending DWR review and approval.

It all looks good to me in GIS. However, a couple minor things on the csv's I downloaded:

1. On Location csv, **name**, **station_id** and **stream_type** fields are the last three columns, but should be earlier in the sheet, after **event_id** and **event_date**. 

2. csv's opened in libre office and google sheets have alternating empty rows/records. Can the empty records be eliminated? (The empty records do not appear in tables opened in ArcPro.)
![image](https://user-images.githubusercontent.com/15659642/62142972-734c2580-b2ac-11e9-9bc1-9a2c275bae3b.png)

**Comment by ToddVolkening** [comment]
We agree with #1 and #2 as described by Nathan above.  

~CW, EE, TV

**Comment by ToddVolkening** [comment]
Looks good.  Thanks

TV and CW
