### ISSUE TITLE
Table - Select Records

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing-query#6]
### User Story
Once the results table is populated with filtered survey event records, I would like to be able to select one or many records in the table. Selected table records should highlight their associated Stations on the map.

- [x] Ctrl-click to select/highlight records from varying rows
- [x] Shift-click ~~AND click-drag~~ to select adjacent rows
- [x] clear selection button
- [x] show number of selected rows & stations

**Comment by stdavis** [comment]
> * Shift-click AND click-drag to select adjacent rows
The grid library that we are using (dgrid) does not support selection by click-dragging. I'm not sure that I've seen that type of UI on the web before. It might be possible to implement but it would take a significant amount of work.

**Comment by ToddVolkening** [comment]
Is Shift-Click still an option for selecting adjacent rows?

TV and CW
